### PR TITLE
add *@wilsaman.eu

### PR DESCRIPTION
**Pull request by stsimb**
```Return-Path: <g>
Received: from mail.wilsaman.eu (mail.wilsaman.eu [213.202.212.37])
	by tux-cave.hellug.gr (8.14.4/8.14.4/Debian-8+deb8u2) with ESMTP id v817Hdfw002807;
	Fri, 1 Sep 2017 10:17:48 +0300
Received: from wilsaman.eu (mail.wilsaman.eu [213.202.212.37])
	by mail.wilsaman.eu (Postfix) with ESMTPA id 021E6B641BF;
	Fri,  1 Sep 2017 09:30:34 +0300 (EEST)
Message-ID: <isluwcb52816462.11582877@mail.wilsaman.eu>
Reply-To: "Maxisize" <isluwcb@wilsaman.eu>
From: "Maxisize" <isluwcb@wilsaman.eu>
To: <market-in1@headhunder.gr>
Subject: =?utf-8?B?zqDOmc6fIM6czpHOms6hzqUsIM6gzpnOnyDOlM6lzp3Okc6kzp8sIM6gzpnOnyDOnM6VzpPOkc6bzp8h?=
Date: Fri, 01 Sep 2017 09:30:40 +0300
Precedence: bulk
List-Id: b71160221v48166048
X-Complaints-To: abuse@wilsaman.eu
List-Unsubscribe: <http://wilsaman.eu/ru/unsubscribe/do>
```

### CODE REVIEW

**Comment by kargig** [comment]
*@wizeminer.eu  has already been previously added. If this is to be merged it needs some cleanup.

**Comment by stsimb** [comment]
I don't see the additions on the current master branch ..

**Comment by kargig** [comment]
This is on master already: https://github.com/kargig/greek-spammers/commit/da6e05f60c1e8e5a8e5ee459b41614d471b3b816

**Comment by stsimb** [comment]
Close this, I'll rebase and submit it again.

**Pull request closed without merging**
