### PR TITLE
Batch

### PR DESCRIPTION
**Pull request by daknob**
Add three entries

### CODE REVIEW

**Comment by kargig** [comment]
1. add some more info for your first two commits please. Are these Greek companies and/or they sent email in Greek?
2. since ebw offers an unsubscribe please use that. If that doesn't work then we can discuss it further but I won't add an eshop to the list that easily.

please make necessary changes and resubmit your PR.

**Comment by daknob** [comment]
Whiskey and Cigars

```
AΛΚΟΟΛ, ΚΑΠΝΟΣ, JAZZ-BLUES μουσική, CIGAR BABES, BUSΙNESS AND DREAMS,
σε μια πόλη που εξακολουθεί να ΖΕΙ.
```

```
Μία ΜΟΝΑΔΙΚΗ ΕΜΠΕΙΡΙΑ για εσάς που θέλετε να ενημερωθείτε, να δοκιμάσετε ή
να προμηθευτείτε με ειδικές εκπτώσεις, Whiskey, Cigars και όχι μόνο, σε μία άκρως
μεθυστική ατμόσφαιρα, όπου οι Cigar Babes θα είναι πάντα πρόθυμες να σας
εξυπηρετήσουν και να σας ενημερώσουν, υπό τους ήχους ζωντανής JAZZ-BLUES μουσικής.
Κατά τη διάρκεια του event, θα διεξαχθούν δημοπρασίες παλαιών όσο και σπάνιων
φιαλών Whiskey και πούρων από σπάνιες συλλογές.

Πάρα πολλοί επώνυμοι και μη από τον Επιχειρηματικό και τον Καλλιτεχνικό χώρο,
Πρεσβείες και Executive Clubs, έχουν ήδη εκδηλώσει έντονα το ενδιαφέρον τους
για το WHISKEY AND CIGARS INTERNATIONAL EVENT.
```

**Comment by daknob** [comment]
Corplace

```
Εταιρείες & Έργα     

Στο Corplace έχουν εγγραφεί:

Στελέχη από όλους τους επιχειρηματικούς κλάδους,
ενώ συνεχίζονται και οι εγγραφές εταιρειών.
```

```
Δίκτυο Εταιρειών

Η έκθεση διαγωνισμών και η στοχευμένη αναζήτηση προμηθευτών, είναι πια γεγονός. Όλα τα μέλη μπορούν να δημοσιεύσουν ΔΩΡΕΑΝ, οποιαδήποτε από τα ακόλουθα έργα:

Δημοπρασία
Διαγωνισμό
Έργο απευθείας ανάθεσης
Έκθεση
Θέση εργασίας
Καινοτομία
Εκδήλωση εταιρείας
Φιλανθρωπία
Business Plan
Σεμινάριο
Επίσης, όλα τα μέλη έχουν το δικαίωμα να συμμετέχουν σε όποιο έργο επιθυμούν.
```

```
Το πρώτο Β2Β στην Ελλάδα, Εταιρείες, Πελάτες, Προμηθευτές, Διαγωνισμοί
```

Let me know if you need more, a total of 5 e-mails from them from what I can tell.

**Comment by daknob** [comment]
About EBW I added the note: for some reason, without receiving a "subscription confirmed" e-mail or something similar, they started e-mailing. This is the first time, and in the past they have been perfect, with `List-Unsubscribe` and unsubscribe links and everything. I will remove it now and if something new comes up, I may open an Issue to discuss it.

**Pull request merged**
